### ISSUE TITLE
Shopping List - Search

### ISSUE THREAD

**Issue by Sebcul** [PhilipRiths/ShoppingListXamarin#20]
- [ ] Searchbar that filters available products

**Comment by alemputes** [comment]
As a User, I want to search my shopping lists

(OLD: As a user I want to search for available products/items)

**Comment by alemputes** [comment]
Question:
1. Should search be implemented at all for shopping lists?
2. If so have the search in the toolbar maybe?
3. When search text changes, UI updates accordingly?

**Comment by alemputes** [comment]
Discussed with Sebbe and this will not be a part of the app, closing.
